"""empty message

Revision ID: 04d8cfb87e66
Revises: 570f1dc522d5
Create Date: 2020-02-01 14:34:36.947635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d8cfb87e66'
down_revision = '570f1dc522d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('words', 'translation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('words', 'word',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('unique_translated_word', 'words', ['word', 'translation'])
    op.drop_constraint('words_word_translation_key', 'words', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('words_word_translation_key', 'words', ['word', 'translation'])
    op.drop_constraint('unique_translated_word', 'words', type_='unique')
    op.alter_column('words', 'word',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('words', 'translation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
