"""empty message

Revision ID: 570f1dc522d5
Revises: f533a8349b44
Create Date: 2020-02-01 14:13:17.441100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570f1dc522d5'
down_revision = 'f533a8349b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('words_word_translation_key', 'words', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('words_word_translation_key', 'words', ['word', 'translation'])
    # ### end Alembic commands ###
